---
- name: sudoers
  become: yes
  lineinfile:
    path: "/etc/sudoers"
    line: "{{ lookup('config', 'DEFAULT_REMOTE_USER') }} ALL=(ALL) NOPASSWD:ALL"
    validate: "/usr/sbin/visudo -cf %s"
    backup: yes
